In [5]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("customer.csv")

In [15]:
df.sample(5)

age  gender   review education purchased
13   57  Female  Average    School        No
16   59    Male     Poor        UG       Yes
20   57  Female  Average    School       Yes
24   16  Female  Average        PG       Yes
3    72  Female     Good        PG        No

* we can see that Review Education Pucharsed is categorical so we can cange that
* for this video we will ingnore age and gender

In [20]:
df = df.iloc[ : ,2:]

In [23]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# Always do Train test Split

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[ : ,-1], test_size = 0.2)

                           

In [67]:
x_train

array([[0., 1.],
       [1., 2.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [2., 2.]])

In [36]:
from sklearn.preprocessing import OrdinalEncoder


In [38]:
oe = OrdinalEncoder(categories = [['Poor','Average','Good'],['School','UG','PG']])

* here we are creating object in class OrdinalEncoder where i am also Giving the order Lower to High if we don't do that it's do Randomly

In [40]:
oe

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [44]:
oe.fit(x_train) # fiting the model

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [59]:
## so Data have nan reomving tem
df = df.dropna()


In [73]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)


/Applications/Anaconda/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [75]:
x_train

array([[0., 1.],
       [1., 2.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [2., 2.]])

In [77]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoder
* usend on OUTPUT

In [80]:
from sklearn.preprocessing import LabelEncoder # we cannot decide order unlike ordinal

In [82]:
le = LabelEncoder()

In [85]:
le.fit(y_train) 

LabelEncoder()

In [87]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [91]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [93]:
y_train

array([1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1])